# default config.yml for MysqlInventoryBridge
# config version 2.4.1

#MySQL Database details
database:
    mysql:
        #MySQL server address
        host: 127.0.0.1
        #MySQL server port (default 3306)
        port: 3306
        #Database name (NOTE! You need to create the database, then the plugin will create the tables.)
        databaseName: 'mydatabase'
        #Tables name (the plugin will auto create it)
        tableName: 'meb_inventory'
        #User name
        user: 'admin'
        #User password
        password: 'cheesecake'
        #SSL connection
        sslEnabled: false
    #Remove inactive users from the database. This maintenance task will start each server start with a 2min delay.
    maintenance:
        #Enable or disable database maintenance.  | (true or false)
        enabled: false
        #Inactivity in days. Default 60 days.
        inactivity: 60
        
        
#Other configurable options
General:
    #Save online players accounts to database task. Disable this task and data will only be saved when the player disconnects.
    #To limit data loss in case the server crashes enable this saving task. It runs async so there will be no lag involved.
    saveDataTask:
        #Enable or disable the data save task. | (true or false)
        enabled: true
        #Time between data saves in minutes. | Default 3 min.
        interval: 3
        #Hide the data save task log messages.
        hideLogMessages: false
    #Login economy sync delay in milliseconds (default 1000 milliseconds = 1 second)
    #This delay is needed in bungeecord setups, because when you move between servers the quit and login takes place almost in the same time.
    loginSyncDelay: 1000
    #Set this to false to disable the sync of players armor. |  (true or false)
    syncArmorEnabled: true
    #Enable modded items support. This will require the ProtocolLib dependency! |  (true or false)
    #This is needed if you experience item data loss on some mods that save NBT data.
    #WARNING! All the servers that are in sync must have this option set the same, or you will lose items.
    enableModdedItemsSupport: false
    #Disable sounds generated by this plugin. The sync confirmation sound for example. | (true or false)
    disableSounds: false
    
    
#Debug console messages.
Debug:
    #Inventory sync debug messages.
    InventorySync: false
    

#Chat Messages with full color and format codes support. Disable any message by setting it to ''  |  Example>  syncComplete: ''
#Minecraft Color and Format Codes: http://minecraft.gamepedia.com/Formatting_codes
ChatMessages:
    syncComplete: '&2[MIB] &aData sync complete!'
    inventorySyncError: '&4[WARNING] &cError loading your inventory! Contact the staff team.'
    inventorySyncBackup: '&6[!] &eRestored the local inventory! Don''t leave items in your inventory when you disconnect!'