name: MysqlInventoryBridge
main: net.craftersland.bridge.inventory.Inv
version: 2.4.1
author: CraftersLand
website: www.craftersland.net
load: STARTUP
api-version: 1.13
description: Sync players inventorys over many servers using MySQL.
softdepend: [ProtocolLib]